# Generated by Django 3.0.10 on 2020-10-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlainText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plain_text', models.CharField(help_text='This is just meant for plain text as an example.', max_length=2000)),
            ],
            options={
                'verbose_name': 'Plain Text',
                'verbose_name_plural': 'Plain Texts',
            },
        ),
    ]
