# Generated by Django 3.0.10 on 2020-10-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plaintext',
            name='plain_text',
            field=models.TextField(help_text='This is just meant for plain text as an example.'),
        ),
    ]
